### ISSUE TITLE
problem with same class name

### ISSUE THREAD

**Issue by ravishakya** [akzhy/scrollbot#2]
First of all great plugin.

I have four class name all are same names. i want scroll in the four class name so when i use this code 

var custom1 = new scrollbot(".custom-scroll");

only the first element is selected and works but the last three doesn't works. any solutions ??

**Comment by akzhy** [comment]
@ravishakya 
Hi,
Currently only one element is selected by default, i will try to change it in the upcoming versions.
For now, if your custom scrolls are the only child elements of it's parent, then you can try this example using `nth-child`. See [fiddle](https://jsfiddle.net/akzhy/u0zrpxrg/)
